clone_folder: c:\projects\lazyflow

environment:
  ENV_NAME: test-env
  # set miniconda version explicitly
  MINICONDA: C:\Miniconda37-x64
  IlASTIK_ROOT: C:\ilastik

install:
  - set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - activate base
  - cd \
  # Get the current master of all submodules
  - git clone https://github.com/ilastik/ilastik-meta %ILASTIK_ROOT%\ilastik-meta
  - cd %ILASTIK_ROOT%\ilastik-meta
  - git submodule update --init --recursive
  - git submodule foreach "git checkout master"
  - ps: rm -Force -Recurse $env:ILASTIK_ROOT\ilastik-meta\lazyflow
  - timeout 10
  # replace with whatever version of lazyflow triggered the appveyor
  - ps: cp -recurse C:\projects\lazyflow $env:ILASTIK_ROOT\ilastik-meta\lazyflow
  - timeout 10
  - cd %ILASTIK_ROOT%\ilastik-meta
  - >
    python ilastik/scripts/devenv.py create -n %ENV_NAME%
    -p ilastik-dependencies-no-solvers pytest-cov coveralls black
    -c ilastik-forge conda-forge defaults

build: off

test_script:
  - set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - activate %ENV_NAME%
  - cd %ILASTIK_ROOT%\ilastik-meta\lazyflow
  - >
      pytest
      --capture=no
      --junitxml=nosetests.lazyflow.xml

on_finish:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
