clone_folder: c:\projects\lazyflow

environment:
  ENV_NAME: test-env
  # set miniconda version explicitly
  MINICONDA: C:\Miniconda36-x64

 
cache:
# modify this file in order to delete the cache; or use CURL (with authorization header):
# DELETE https://ci.appveyor.com/api/projects/{accountName}/{projectSlug}/buildcache
  - '%MINICONDA%\envs\%ENV_NAME% -> appveyor.yml'

install:
  - set DEV_PREFIX=%MINICONDA%/envs/%ENV_NAME%
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - ps: >-
      If (![System.IO.File]::Exists($env:DEV_PREFIX)) {
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda create -q --yes -n $env:ENV_NAME -c ilastik-forge -c conda-forge python=3.6 numpy=1.12 ilastik-dependencies-no-solvers
      }
  - activate %ENV_NAME%
  - cd \
  # Get the current master of all submodules
  - git clone https://github.com/ilastik/ilastik-meta c:\ilastik\ilastik-meta
  - cd ilastik\ilastik-meta
  - git submodule update --init --recursive
  - git submodule foreach "git checkout master"
  # Remove the conda ilastik-meta
  - conda remove ilastik-meta
  - ps: rm -Force -Recurse c:\ilastik\ilastik-meta\lazyflow
  - timeout 10
  # replace with whatever version of lazyflow triggered the appveyor
  - ps: cp -recurse C:\projects\lazyflow c:\ilastik\ilastik-meta\lazyflow
  - timeout 10
  # Point to the current ilastik-meta
  - set ILASTIK_PTH=%MINICONDA%/envs/%ENV_NAME%/Lib/site-packages/ilastik-meta.pth
  - echo C:/ilastik/ilastik-meta/lazyflow > %ILASTIK_PTH%
  - echo C:/ilastik/ilastik-meta/volumina >> %ILASTIK_PTH%
  - echo C:/ilastik/ilastik-meta/ilastik >> %ILASTIK_PTH%

build: off

test_script:
  - set DEV_PREFIX=%MINICONDA%/envs/%ENV_NAME%
  - activate %ENV_NAME%
  - cd \
  - cd ilastik\ilastik-meta\lazyflow\tests
  - set Path=C:\ilastik\scripts;%Path%
  - >
      nosetests
      --nologcapture
      --ignore-files=testInterpolatedFeatures.py
      --with-xunit
      --xunit-file=nosetests.lazyflow.xml
      .

# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
